spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET_KEY}
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]
  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  token-validity-in-seconds: 86400

aes:
  key: ${ASE_KEY}

#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
    jdbc: off
    sqltiming: debug
    org:
      springframework:
        security: DEBUG

server:
  port: 8080

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: ${APP_AUTH_TOKEN_SECRET}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
---
spring:
  application:
    name: vue-art
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /swagger-ui.html          # UI ?? ??
  packages-to-scan: com.vueart.api.controller  # ??? ??? ??
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true

#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
    jdbc: off
    sqltiming: debug

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

aes:
  key: ${ASE_KEY}
server:
  port: 8080

---
spring:
  application:
    name: vue-art
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html         # Swagger UI ?? ??
    groups-order: DESC             # ?? ??
    tags-sorter: alpha             # ?? ?? ??
    operations-sorter: method      # ??? ? ??
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /swagger-ui.html          # UI ?? ??
  packages-to-scan: com.vueart.api.controller  # ??? ??? ??
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true
