spring:
  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]
  profiles:
    active: local

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

aes:
  key: ${ASE_KEY}

#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
    jdbc: off
    sqltiming: debug

server:
  port: 8080

---
spring:
  application:
    name: vue-art
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html         # Swagger UI ?? ??
    groups-order: DESC             # ?? ??
    tags-sorter: alpha             # ?? ?? ??
    operations-sorter: method      # ??? ? ??
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /swagger-ui.html          # UI ?? ??
  packages-to-scan: com.vueart.api.controller  # ??? ??? ??
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true

#logging
logging:
  level:
    root: info
    '[org.springframework.web]': debug
    jdbc: off
    sqltiming: debug

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

aes:
  key: ${ASE_KEY}
server:
  port: 8080

---
spring:
  application:
    name: vue-art
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html         # Swagger UI ?? ??
    groups-order: DESC             # ?? ??
    tags-sorter: alpha             # ?? ?? ??
    operations-sorter: method      # ??? ? ??
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
    - /swagger-ui.html          # UI ?? ??
  packages-to-scan: com.vueart.api.controller  # ??? ??? ??
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true
